
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false